name: CI
on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.1
      - run: npm ci # equivalent to npm install, but does a clean install
      - run: npm ci --prefix backend # equivalent to npm install, but does a clean install
      - run: npm ci --prefix backend/src # equivalent to npm install, but does a clean install
      - run: npm test
      - run: npm run build
